### ISSUE TITLE
Path File Raises ModuleNotFound Error When Imported

### ISSUE THREAD

**Issue by Morgan-Phoenix** [pybash1/py_everything#42]
When I import something form the path file, it gives the error that a module named "error" is not found

1. from py_everything import path
3. Run the code
4. Error occurs
The "error" module is not found as when the path file is imported the location of the call changes and hence no file named "error" is found

**Device:**
 - OS: Windows
 - Python Version: 3.9.5
 - Package Version: 2.1.0

**Comment by pybash1** [comment]
Fixed in latest commit to `bug_fixes` branch.
