### ISSUE TITLE
htmlXml Result Hard To Match

### ISSUE THREAD

**Issue by Morgan-Phoenix** [pybash1/py_everything#46]
The Result Returned By Any Function of htmlXml.py is hard to trace back to where it is in the html or XML file 
It Would be better if the result comes with line numbers too

**Comment by pybash1** [comment]
Well if it had to come with line numbers then it would need to be in the form a `dict` or `tuple`. And that would make it much more complex.

**Comment by pybash1** [comment]
It is a good idea though. I am going to keep it in consideration.

**Comment by Morgan-Phoenix** [comment]
We can use `dict`. It's easy to match than a list, if list is a necessity than we can use arrows

**Comment by pybash1** [comment]
I was thinking about tuples, inside a dict as like this - 
`[(1, '<div>test</div>'), (5, <div>demo</div>), (7, <div>another div</div>)]`
And you can probably see by the trend that the first value of the tuple is the line number and the second one is the matched line.

**Comment by Morgan-Phoenix** [comment]
Yeah this is even better

**Comment by pybash1** [comment]
Ok, so will you start work on it or I will?

**Comment by Morgan-Phoenix** [comment]
You do I'm off for today

**Comment by pybash1** [comment]
Ok.
