### ISSUE TITLE
(FLK-W293) Blank line contains whitespace

### ISSUE THREAD

**Issue by pybash1** [pybash1/py_everything#57]
## Description
Blank lines should not contain any tabs or spaces.

## Occurrences
There are 168 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/pybash1/py_everything/issue/FLK-W293/occurrences/](https://deepsource.io/gh/pybash1/py_everything/issue/FLK-W293/occurrences/)

**Comment by Morgan-Phoenix** [comment]
There are no occurrence shown in the given link

**Comment by pybash1** [comment]
Yes it has been ignored temporarily but they are there

**Comment by Morgan-Phoenix** [comment]
Do I have to find everyone of them
Will I not get the list that I got in #58 ?

**Comment by pybash1** [comment]
Ok wait I will unignore them then you can revisit the link.

**Comment by Morgan-Phoenix** [comment]
Ok

**Comment by pybash1** [comment]
@Morgan-Phoenix I unignored the issue but it doesn't seem to reappear. Let me see what I can do.

**Comment by Morgan-Phoenix** [comment]
Ok otherwise we can just leave it

**Comment by pybash1** [comment]
Yes that is an option.

**Comment by pybash1** [comment]
@Morgan-Phoenix you can revisit the link now again. It will show all occurences. You can fix them.
