### ISSUE TITLE
(PTC-W0048) `if` statements can be merged

### ISSUE THREAD

**Issue by pybash1** [pybash1/py_everything#58]
## Description
Nested `if` statements can be collapsed into a single `if` statement by separating their condition using `and` operator. Merging collapsible `if` statements increases the code&#x27;s readability.

### Not preferred:
```python
if condition1:
    if condition2:
        dosomething()
```

#### Preferred:
```python
if condition1 and condition2:
       dosomething()
```

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/pybash1/py_everything/issue/PTC-W0048/occurrences/](https://deepsource.io/gh/pybash1/py_everything/issue/PTC-W0048/occurrences/)

**Comment by Morgan-Phoenix** [comment]
working on this
