### ISSUE TITLE
Wrong testing 

### ISSUE THREAD

**Issue by Morgan-Phoenix** [pybash1/py_everything#67]
The tests that are running are wrong.
`evalexp` requires a `int` but `str` was given

**Comment by pybash1** [comment]
No tests are not wrong, it has to take in a str since it is a expression not just a number.

**Comment by Morgan-Phoenix** [comment]
But it changed as I changed the func.

**Comment by pybash1** [comment]
What do you mean how can I provide a mathematical expression as a n integer to the function? 

For example - `1-1+5*4+2`
How can I convert this to a integer?

**Comment by pybash1** [comment]
Tests are fine
