### ISSUE TITLE
[FEATURE] Add function that converts any roman numeral to an integer

### ISSUE THREAD

**Issue by tosinolawore** [pybash1/py_everything#85]
**Conversion from roman numerals to an integer**
Create a python function that converts any roman numeral to an integer. Roman numerals could be confusing at times, a function that converts them to an easy to understand integer would be helpful.

**Comment by tosinolawore** [comment]
Hi @pybash1 @Morgan-Phoenix , I opened a PR #86 to address this issue. Would you want to check it out?

**Comment by pybash1** [comment]
@tosinolawore Closing as fixed in #86

**Comment by tosinolawore** [comment]
@pybash1 Great
